apiVersion: v1
kind: Service
metadata:
  name: ecom-service
spec:
  type: LoadBalancer
  selector:
    app: ecom-project
  ports:
    - protocol: TCP
      port: 80         # The port you'll use in the browser
      targetPort: 5000 # The port your container is listening on